### ISSUE TITLE
Claims, view slots and the camera wall

### ISSUE THREAD

**Issue by Timwi** [samfun123/KtaneTwitchPlays#255]
I would like to propose the following changes to the behavior of !view and the camera wall.

* If you !view a module, and you're already occupying a view slot, and all other view slots have a claimed module in them, the new module should replace the existing view slot. (In other words, a player can only take up two view slots if there are view slots to spare.) Pinned views (such as FMN) are excepted.

* If you !view a module, and you are not using a view slot, but someone else is using two, replace one of that player's.

* If you !view a module and there are already 6 unique players taking up the view slots, the camera wall should automatically engage and show all claimed modules. Bonus points if it also automatically runs !modules instead of showing a mostly black screen.

* When a module is solved, reevaluate the situation to see if a claimed module can be brought back into view and/or the camera wall can be turned back off.

**Comment by CaitSith2** [comment]
* In the case of camera wall being enabled, a !bomb turn should automatically move unclaimed modules currently occupying a camera slot to the back of the line, so that the next set of modules available will show up in the unclaimed camera slots.  In this way, !bomb turn will still be effective when the camera wall is enabled.

**Comment by red031000** [comment]
Can we close this issue now? From what I can tell, most of this behaviour is happening now
